## One Hot Encoding

In [1]:
import numpy as np
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [2]:
df_main = pd.read_csv(r'C:\Users\Nutzer\Desktop\BAExperiment\new_table.csv')

df_main.head()

VOUCHER NUMBER      AMOUNT  CHECK DATE  \
0   PV27242780609  4260645.83  06/18/2024   
1   PV27232768083       94.55  12/29/2023   
2   CVIP232100094   152170.84  06/08/2023   
3  PVCI23CI705786    63250.00        2021   
4  PVCI23CI705786    38554.81        2021   

                        DEPARTMENT NAME CONTRACT NUMBER  \
0                  DEPARTMENT OF HEALTH              DV   
1                      DEPT OF AVIATION              DV   
2                 DEPARTMENT OF HOUSING          190668   
3   DEPT OF FAMILY AND SUPPORT SERVICES          117293   
4  CHICAGO DEPARTMENT OF TRANSPORTATION          124392   

                                         VENDOR NAME  CASHED  
0                        USI INSURANCE SERVICES LLC.   False  
1                                        PEARL KOCUR   False  
2               LAWYERS COMMITTEE FOR BETTER HOUSING    True  
3                    YOUNG MEN'S EDUCATIONAL NETWORK    True  
4  TRAVELERS & IMMIGRANTS AID'S HEARTLAND ALLIANC...    True

In [3]:
ohe= OneHotEncoder()

In [4]:
print(ohe)

OneHotEncoder()


In [10]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Load the CSV file
df = pd.read_csv(r'C:\Users\Nutzer\Desktop\BAExperiment\new_table.csv')

# Initialize OneHotEncoder with sparse_output=True (for newer versions of scikit-learn)
ohe = OneHotEncoder(sparse_output=True)

# Fit and transform the relevant columns in the DataFrame
# Replace 'CASHED', 'VOUCHER NUMBER', 'DEPARTMENT NAME' with your actual column names
encoded_sparse = ohe.fit_transform(df[["CASHED", "VOUCHER NUMBER", "DEPARTMENT NAME"]])

# Now encoded_sparse is a sparse matrix
# Print the sparse matrix information
print(f"Sparse matrix shape: {encoded_sparse.shape}")
print(f"Sparse matrix type: {type(encoded_sparse)}")



Sparse matrix shape: (379899, 242416)
Sparse matrix type: <class 'scipy.sparse._csr.csr_matrix'>


In [6]:
df = pd.read_csv(r'C:\Users\Nutzer\Desktop\BAExperiment\new_table.csv')


In [12]:
df["VOUCHER NUMBER"].unique()

array(['PV27242780609', 'PV27232768083', 'CVIP232100094', ...,
       'PV27222763096', 'PV27222702155', 'PVRF212204731'], dtype=object)

In [13]:
df["DEPARTMENT NAME"].unique()

array(['DEPARTMENT OF HEALTH', 'DEPT OF AVIATION',
       'DEPARTMENT OF HOUSING', 'DEPT OF FAMILY AND SUPPORT SERVICES',
       'CHICAGO DEPARTMENT OF TRANSPORTATION',
       'DEPARTMENT OF WATER MANAGEMENT', 'DEPT OF GENERAL SERVICES',
       'DEPARTMENT OF ENVIROMENT', 'DEPT OF FLEET MGMT',
       'DEPARTMENT OF BUILDINGS',
       'DEPARTMENT OF CHILDREN AND YOUTH SERVICES',
       'DEPT OF BUSINESS AFFAIRS & CONSUMER PROTECTION',
       'DEPARTMENT OF FINANCE', 'OFFICE FOR PEOPLE WITH DISABILITIES',
       'OFFICE OF EMERGENCY COMMUNICATION',
       'DEPARTMENT OF CULTURAL AFFAIRS', 'DEPT OF PLANNING & DEVELOPMENT',
       'PLANNING & DEVELOPMENT', 'FIRE DEPARTMENT',
       'DEPARTMENT OF PERSONNEL', 'DEPT OF STREETS & SANITATION',
       'DEPARTMENT OF LAW',
       'DEPARTMENT OF CULTURAL AFFAIRS AND SPECIAL EVENTS',
       'DEPT OF BUSINESS & INFORMATION SERVICES',
       'DEPARTMENT OF HUMAN SERVICES',
       'OFFICE OF PUBLIC SAFETY ADMINISTRATION', 'DEPARTMENT OF POLICE',
    

In [14]:
df["CASHED"].unique()

array([False,  True])

In [17]:
ohe.fit_transform(df[["CASHED" ]]).toarray()

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [21]:
feature_arry= ohe.fit_transform(df[["CASHED"]]).toarray()

In [19]:
ohe.categories_

[array([False,  True])]

In [23]:
feature_labels= ohe.categories_

In [24]:
np.array(feature_labels).ravel()

array([False,  True])

In [25]:
pd.DataFrame(feature_arry, columns=feature_labels)

False True 
0        1.0   0.0
1        1.0   0.0
2        0.0   1.0
3        0.0   1.0
4        0.0   1.0
...      ...   ...
379894   0.0   1.0
379895   0.0   1.0
379896   0.0   1.0
379897   0.0   1.0
379898   0.0   1.0

[379899 rows x 2 columns]

In [30]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# Step 1: Load dataset from CSV
df = pd.read_csv(r'C:\Users\Nutzer\Desktop\BAExperiment\new_table.csv')  # Replace with the actual path to your CSV file

# Step 2: Replace NaN values in the 'CASHED' column (you can use True or False)
df['CASHED'] = df['CASHED'].fillna(False)

# Step 3: Initialize OneHotEncoder
ohe = OneHotEncoder()

# Step 4: Apply OneHotEncoder to the 'CASHED' column
feature_array = ohe.fit_transform(df[['CASHED']]).toarray()

# Step 5: Convert the one-hot encoded array to a DataFrame with appropriate column names
feature_df = pd.DataFrame(feature_array, columns=ohe.categories_[0])

# Step 6: Concatenate the original DataFrame with the one-hot encoded DataFrame
df_combined = pd.concat([df.reset_index(drop=True), feature_df.reset_index(drop=True)], axis=1)

# Step 7: Save the combined DataFrame as a CSV file
output_path = r'C:\Users\Nutzer\Desktop\BAExperiment\encoded_table.csv'  # Specify where you want to save the file
df_combined.to_csv(output_path, index=False)  # Save as CSV without the index column

print(f"File saved successfully at: {output_path}")


File saved successfully at: C:\Users\Nutzer\Desktop\BAExperiment\encoded_table.csv


## zweite Catagorie encoden

In [31]:
df = pd.read_csv(r'C:\Users\Nutzer\Desktop\BAExperiment\encoded_table.csv')


In [33]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Step 1: Load dataset
df = pd.read_csv(r'C:\Users\Nutzer\Desktop\BAExperiment\encoded_table.csv')

# Step 2: Initialize OneHotEncoder with sparse_output=True (which is default for newer versions)
ohe = OneHotEncoder(sparse_output=True)

# Step 3: Apply OneHotEncoder to the 'VOUCHER NUMBER' column
encoded_sparse = ohe.fit_transform(df[["VOUCHER NUMBER"]])

# Step 4: Use the sparse matrix directly or save it
print(f"Sparse matrix shape: {encoded_sparse.shape}")
print(f"Non-zero elements: {encoded_sparse.nnz}")


Sparse matrix shape: (379899, 242352)
Non-zero elements: 379899


In [34]:
# Frequency encoding for high cardinality columns like 'VOUCHER NUMBER'
df['VOUCHER NUMBER_FREQ'] = df['VOUCHER NUMBER'].map(df['VOUCHER NUMBER'].value_counts(normalize=True))

print(df[['VOUCHER NUMBER', 'VOUCHER NUMBER_FREQ']].head())


   VOUCHER NUMBER  VOUCHER NUMBER_FREQ
0   PV27242780609             0.000003
1   PV27232768083             0.000003
2   CVIP232100094             0.000003
3  PVCI23CI705786             0.053959
4  PVCI23CI705786             0.053959


In [38]:
# Frequency encoding for high cardinality columns like 'VOUCHER NUMBER'
df['DEPARTMENT NAME_FREQ'] = df['DEPARTMENT NAME'].map(df['DEPARTMENT NAME'].value_counts(normalize=True))

print(df[['DEPARTMENT NAME', 'DEPARTMENT NAME_FREQ']].head())

                        DEPARTMENT NAME  DEPARTMENT NAME_FREQ
0                  DEPARTMENT OF HEALTH              0.141327
1                      DEPT OF AVIATION              0.139263
2                 DEPARTMENT OF HOUSING              0.013609
3   DEPT OF FAMILY AND SUPPORT SERVICES              0.198629
4  CHICAGO DEPARTMENT OF TRANSPORTATION              0.127026


##  Label Encoding

In [35]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# Apply LabelEncoder to the 'VOUCHER NUMBER' column
df['VOUCHER_NUMBER_ENCODED'] = le.fit_transform(df['VOUCHER NUMBER'])

print(df[['VOUCHER NUMBER', 'VOUCHER_NUMBER_ENCODED']].head())


   VOUCHER NUMBER  VOUCHER_NUMBER_ENCODED
0   PV27242780609                   89193
1   PV27232768083                   75363
2   CVIP232100094                    7410
3  PVCI23CI705786                  208890
4  PVCI23CI705786                  208890


In [37]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split  # Example import for data splitting

# Set random seed
random_seed = 42

# Step 1: Load dataset
df = pd.read_csv(r'C:\Users\Nutzer\Desktop\BAExperiment\encoded_table.csv')

# Step 2: Initialize LabelEncoder
le_voucher = LabelEncoder()
le_department = LabelEncoder()

# Step 3: Apply LabelEncoder to the 'VOUCHER NUMBER' column
df['VOUCHER_NUMBER_ENCODED'] = le_voucher.fit_transform(df['VOUCHER NUMBER'])

# Step 4: Apply LabelEncoder to the 'DEPARTMENT NAME' column
df['DEPARTMENT_NAME_ENCODED'] = le_department.fit_transform(df['DEPARTMENT NAME'])

# Example of using the random seed in train_test_split (if needed)
# Split data into train and test sets
train_df, test_df = train_test_split(df, test_size=0.2, random_state=random_seed)

# Save the DataFrame with the label encoded columns to a CSV file
output_path = r'C:\Users\Nutzer\Desktop\BAExperiment\label_encoded_table.csv'  # Specify the output path
df.to_csv(output_path, index=False)  # Save to CSV without the index

print(f"CSV file saved successfully at: {output_path}")


CSV file saved successfully at: C:\Users\Nutzer\Desktop\BAExperiment\label_encoded_table.csv


##  Zweite Dataset


In [1]:
import numpy as np
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [2]:
df_main = pd.read_csv(r'C:\Users\Nutzer\Desktop\BAExperiment\city_payments_fy2017.csv')

df_main.head()

fy  fm  check_date   document_no  dept           department_title  char_  \
0  2017  10  2017-04-12  CHEK17119771    42                42 COMMERCE      2   
1  2017  12  2017-06-09  ACHD17177233    26  26 LICENSES & INSPECTIONS      2   
2  2017   5  2016-11-25  CHEK17063736    44                     44 LAW      2   
3  2017   1  2016-07-07  CHEK17000247    11                  11 POLICE      2   
4  2017   1  2016-07-08  ACHD17000233    23                 23 PRISONS      3   

             character_title sub_obj                        sub_obj_title  \
0    02 PURCHASE OF SERVICES     231                  OVERTIME MEALS 0231   
1    02 PURCHASE OF SERVICES     211                  TRANSPORTATION 0211   
2    02 PURCHASE OF SERVICES     258                 COURT REPORTERS 0258   
3    02 PURCHASE OF SERVICES     260  REPAIR AND MAINTENANCE CHARGES 0260   
4  03 MATERIALS AND SUPPLIES     313                            FOOD 0313   

                    vendor_name doc_ref_no_prefix  \
0                  EAT AT JOE'S              PVXX   
1   L & I  TRAVEL IMPREST FUND              PVXX   
2  MARLENE BELL REPORTING, INC.              PVXX   
3    RICOH AMERICAS CORPORATION              VCXX   
4          PHILADELPHIA PRISONS              PCXX   

  doc_ref_no_prefix_definition contract_number contract_description  \
0              payment voucher             NaN                  NaN   
1              payment voucher             NaN                  NaN   
2              payment voucher             NaN                  NaN   
3                  procurement             NaN                  NaN   
4                   petty cash             NaN                  NaN   

   transaction_amount  
0               66.82  
1              127.33  
2              454.20  
3               50.00  
4               71.92

In [3]:
ohe= OneHotEncoder()

In [4]:
print(ohe)

OneHotEncoder()


In [10]:
df = pd.read_csv(r'C:\Users\Nutzer\Desktop\BAExperiment\city_payments_fy2017.csv')

In [12]:
df["contract_number"].unique()

array([nan, '150234', '150159', ..., '1720535', '1720368', '1720630'],
      dtype=object)

In [13]:
df["contract_description"].unique()

array([nan, 'Supplies for Child Care Room', 'Iron Pipe', ...,
       'Early Intervention Serv', 'MH Crisis Response Center',
       'Trauma Education Program'], dtype=object)

In [14]:
df["doc_ref_no_prefix_definition"].unique()

array(['payment voucher', 'procurement', 'petty cash',
       'professional services', 'auto parts', 'library books',
       'court appointed attorneys', 'American Express travel vouchers',
       'reimbursable expense vouchers for City employees',
       'monthly rent and quarterly MH/MR', 'funeral directors', nan],
      dtype=object)

In [16]:
df["doc_ref_no_prefix"].unique()

array(['PVXX', 'VCXX', 'PCXX', 'PVMD', 'PVFM', 'PVFL', 'PVAT', 'PVTR',
       'RPXX', 'PVOS', 'PVFD', nan], dtype=object)

In [17]:
df["sub_obj"].unique()

array(['231', '211', '258', '260', '313', '317', '285', '325', '323',
       '253', '328', '250', '256', '306', '290', '322', '335', '251',
       '307', '0604P', '255', '428', '201', '280', '210', '305', '314',
       '266', '420', '405', '430', '304', '312', '06IBP', '612', '0636P',
       '240', '264', '310', '324', '209', '259', '0612P', '212', '0605P',
       '311', '230', '308', '636', '674', '604', '605', '0611P', '309',
       '318', '680', '205', '345', '427', '202', '0610P', '614', '699',
       '424', '262', '316', '220', '401', '517', '410', '695', '320',
       '705', '221', '326', '216', '601', '630', '658', '652', '215',
       '418', '417', '0641P', '286', '0606P', '411', '681', '0664P',
       '301', '672', '300', '419', '617', '302', '506', '640', '330',
       '643', '412', '400', '0672P', '299', '660', '421', '257', '284',
       '701', '702', '281', '252', '654', '0662P', '403', '0671P', '638',
       '295', '0608P', '342', '282', '631', '340', '0699P', '664', '222

In [18]:
df["transaction_amount"].unique()

array([   66.82,   127.33,   454.2 , ...,  1111.6 , 28295.13, 57874.4 ])

In [20]:
df["char_"].unique()

array([2, 3, 6, 4, 5, 7], dtype=int64)

In [21]:
df["dept"].unique()

array([42, 26, 44, 11, 23, 22, 28, 48, 10, 68, 25, 24, 12, 52, 14, 16, 69,
       63, 13,  8, 36, 35,  1, 31,  4, 56, 38,  6, 53, 70, 73, 20, 61, 45,
       15, 37, 51,  5, 41, 65, 59, 30,  3, 40, 54, 49, 58, 34, 47, 46, 55,
       27, 17, 66, 67, 62, 50, 18], dtype=int64)

In [22]:
df["document_no"].unique()

array(['CHEK17119771', 'ACHD17177233', 'CHEK17063736', ...,
       'CHEK17114422', 'CHEK17114423', 'CHEK17114424'], dtype=object)

In [23]:
df["fm"].unique()

array([10, 12,  5,  1,  2, 11,  3,  4,  6,  7,  8,  9], dtype=int64)

In [24]:
df["fy"].unique()

array([2017], dtype=int64)

In [25]:
df["department_title"].unique()

array(['42 COMMERCE', '26 LICENSES & INSPECTIONS', '44 LAW', '11 POLICE',
       '23 PRISONS', '22 HUMAN SERVICES', '28 WATER',
       '48 MAYOR-OFFICE OF THE INSPECTOR GENERAL', '10 MANAGING DIRECTOR',
       '68 REGISTER OF WILLS', '25 FLEET MANAGEMENT',
       '24 OFFICE OF SUPPORTIVE HOUSING', '12 STREETS', '52 FREE LIBRARY',
       '14 HEALTH', '16 RECREATION', '69 DISTRICT ATTORNEY',
       '63 BOARD OF REVISION OF TAXES', '13 FIRE',
       "08 MAYOR'S OFFICE-COMMUNITY SERVICES", '36 REVENUE',
       '35 DIRECTOR OF FINANCE', '01 CITY COUNCIL', '31 RECORDS',
       '04 MDO-OFFICE OF TECHNOLOGY', '56 PERSONNEL', '38 PROCUREMENT',
       '06 OFFICE OF HOUSING', '53 BOARD OF PENSIONS', '70 SHERIFF',
       '73 CITY COMMISSIONERS', '20 PUBLIC PROPERTY',
       '61 CITY CONTROLLER', '45 BOARD OF ETHICS',
       '15 OFFICE OF BH/MR SERVICES', '37 SINKING FUND COMMISSION',
       '51 CITY PLANNING COMMISSION', "05 MAYOR'S OFFICE",
       '41 CITY REPRESENTATIVE',
       '65 MAYOR-OFFICE

In [26]:
df["character_title"].unique()

array(['02 PURCHASE OF SERVICES', '03 MATERIALS AND SUPPLIES',
       '06 REAL PROPERTY', '04 EQUIPMENT',
       '05 CONTRIBUTIONS,INDEMNITIES,REFDS,TAXES', '07 DEBT SERVICE'],
      dtype=object)

## Label Encoding

In [27]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# Apply LabelEncoder to the 'VOUCHER NUMBER' column
df['doc_ref_no_prefix_ENCODED'] = le.fit_transform(df['doc_ref_no_prefix'])

print(df[['doc_ref_no_prefix', 'doc_ref_no_prefix_ENCODED']].head())


  doc_ref_no_prefix  doc_ref_no_prefix_ENCODED
0              PVXX                          8
1              PVXX                          8
2              PVXX                          8
3              VCXX                         10
4              PCXX                          0


## Identify columns with missing values and categorical data

In [28]:
# Identify columns with missing values and categorical data
missing_categorical = [var for var in df.columns if df[var].isnull().mean() > 0 and df[var].dtype == 'object']


In [29]:
missing_categorical

['doc_ref_no_prefix',
 'doc_ref_no_prefix_definition',
 'contract_number',
 'contract_description']

## Count of missing Data

## doc_ref_no_prefix

In [30]:
# Check the percentage of missing values in the 'VOUCHER NUMBER' and 'DEPARTMENT NAME' columns
missing_percentage = df[['doc_ref_no_prefix', 'doc_ref_no_prefix_definition', 'contract_number',
 'contract_description' ]].isnull().mean()

print(missing_percentage)

doc_ref_no_prefix               0.000213
doc_ref_no_prefix_definition    0.000213
contract_number                 0.515911
contract_description            0.515911
dtype: float64


In [31]:
# Print the percentage of missing values for both columns
for column, percentage in missing_percentage.items():
    print(f"Percentage of missing values in '{column}': {percentage:.2%}")


Percentage of missing values in 'doc_ref_no_prefix': 0.02%
Percentage of missing values in 'doc_ref_no_prefix_definition': 0.02%
Percentage of missing values in 'contract_number': 51.59%
Percentage of missing values in 'contract_description': 51.59%


In [33]:
# Count the number of missing values in the 'VOUCHER NUMBER' and 'DEPARTMENT NAME' columns
missing_counts = df[['doc_ref_no_prefix', 'doc_ref_no_prefix_definition', 'contract_number',
 'contract_description']].isnull().sum()


# Print the number of missing values for both columns
for column, count in missing_counts.items():
    print(f"Number of missing values in '{column}': {count}")


Number of missing values in 'doc_ref_no_prefix': 51
Number of missing values in 'doc_ref_no_prefix_definition': 51
Number of missing values in 'contract_number': 123248
Number of missing values in 'contract_description': 123248


In [ ]:
'doc_ref_no_prefix',
 'doc_ref_no_prefix_definition',
 'contract_number',
 'contract_description'

In [34]:
# Get the count of each unique value in the 'VOUCHER NUMBER' and 'DEPARTMENT NAME' columns
doc_ref_no_prefix_counts = df['doc_ref_no_prefix'].value_counts()
doc_ref_no_prefix_definition_counts = df['doc_ref_no_prefix_definition'].value_counts()
contract_number_counts = df['contract_number'].value_counts()
contract_description_counts = df['contract_description'].value_counts()



# Print the counts of unique values in both columns
print("Unique value counts for 'doc_ref_no_prefix':")
print(doc_ref_no_prefix_counts)
print("\nUnique value counts for 'doc_ref_no_prefix_definition':")
print(doc_ref_no_prefix_definition_counts)


print("Unique value counts for 'contract_number':")
print(contract_number_counts)
print("\nUnique value counts for 'contract_description':")
print(contract_description_counts)








Unique value counts for 'doc_ref_no_prefix':
doc_ref_no_prefix
VCXX    93119
PVFM    40038
PVMD    36793
PVAT    28521
PVXX    16831
PCXX    12175
PVFL     4702
RPXX     4447
PVTR     1802
PVOS      327
PVFD       88
Name: count, dtype: int64

Unique value counts for 'doc_ref_no_prefix_definition':
doc_ref_no_prefix_definition
procurement                                         93119
auto parts                                          40038
professional services                               36793
court appointed attorneys                           28521
payment voucher                                     16831
petty cash                                          12175
library books                                        4702
reimbursable expense vouchers for City employees     4447
American Express travel vouchers                     1802
monthly rent and quarterly MH/MR                      327
funeral directors                                      88
Name: count, dtype: int64
Unique 

In [37]:
import pandas as pd
import numpy as np

# Load the dataset from a CSV file (adjust the path as needed)
df_main = pd.read_csv(r'C:\Users\Nutzer\Desktop\BAExperiment\city_payments_fy2017.csv')

# Display the first few rows of the dataset to understand its structure
print(df_main.head())

# Define possible fill values for each column
doc_ref_no_prefix_fill_values = ['VCXX', 'PVFM', 'PVMD', 'PVAT', 'PVXX', 'PCXX', 'PVFL', 'RPXX', 'PVTR', 'PVOS', 'PVFD']
doc_ref_no_prefix_definition_fill_values = ['procurement', 'auto parts', 'professional services', 'court appointed attorneys', 'payment voucher', 'petty cash', 'library books', 'reimbursable expense vouchers for City employees', 'American Express travel vouchers', 'monthly rent and quarterly MH/MR', 'funeral directors']
contract_number_fill_values = df_main['contract_number'].dropna().unique()
contract_description_fill_values = df_main['contract_description'].dropna().unique()

# Set random seed for reproducibility
np.random.seed(42)

# Function to randomly select a fill value
def random_fill(fill_values):
    return np.random.choice(fill_values)

# Apply random fill to missing values in 'doc_ref_no_prefix'
df_main['doc_ref_no_prefix'] = df_main['doc_ref_no_prefix'].apply(lambda x: random_fill(doc_ref_no_prefix_fill_values) if pd.isnull(x) else x)

# Apply random fill to missing values in 'doc_ref_no_prefix_definition'
df_main['doc_ref_no_prefix_definition'] = df_main['doc_ref_no_prefix_definition'].apply(lambda x: random_fill(doc_ref_no_prefix_definition_fill_values) if pd.isnull(x) else x)

# Apply random fill to missing values in 'contract_number'
df_main['contract_number'] = df_main['contract_number'].apply(lambda x: random_fill(contract_number_fill_values) if pd.isnull(x) else x)

# Apply random fill to missing values in 'contract_description'
df_main['contract_description'] = df_main['contract_description'].apply(lambda x: random_fill(contract_description_fill_values) if pd.isnull(x) else x)

# Apply mean or median for numeric columns if needed
for column in df_main.select_dtypes(include=[np.number]).columns:
    df_main[column].fillna(df_main[column].mean(), inplace=True)

# Apply mode for categorical columns if needed
for column in df_main.select_dtypes(include=[object]).columns:
    df_main[column].fillna(df_main[column].mode()[0], inplace=True)

# Verify if there are any missing values left
missing_counts_after = df_main.isnull().sum()
print("Missing values after filling:\n", missing_counts_after)

# Save the updated DataFrame to a new CSV file
new_file_path = r'C:\Users\Nutzer\Desktop\BAExperiment\filled_data.csv'
df_main.to_csv(new_file_path, index=False)

print(f"Updated dataset saved to: {new_file_path}")

     fy  fm  check_date   document_no  dept           department_title  char_  \
0  2017  10  2017-04-12  CHEK17119771    42                42 COMMERCE      2   
1  2017  12  2017-06-09  ACHD17177233    26  26 LICENSES & INSPECTIONS      2   
2  2017   5  2016-11-25  CHEK17063736    44                     44 LAW      2   
3  2017   1  2016-07-07  CHEK17000247    11                  11 POLICE      2   
4  2017   1  2016-07-08  ACHD17000233    23                 23 PRISONS      3   

             character_title sub_obj                        sub_obj_title  \
0    02 PURCHASE OF SERVICES     231                  OVERTIME MEALS 0231   
1    02 PURCHASE OF SERVICES     211                  TRANSPORTATION 0211   
2    02 PURCHASE OF SERVICES     258                 COURT REPORTERS 0258   
3    02 PURCHASE OF SERVICES     260  REPAIR AND MAINTENANCE CHARGES 0260   
4  03 MATERIALS AND SUPPLIES     313                            FOOD 0313   

                    vendor_name doc_ref_no_prefix 

C:\Users\Nutzer\AppData\Local\Temp\ipykernel_12036\782417766.py:37: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_main[column].fillna(df_main[column].mean(), inplace=True)
C:\Users\Nutzer\AppData\Local\Temp\ipykernel_12036\782417766.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a 

Missing values after filling:
 fy                              0
fm                              0
check_date                      0
document_no                     0
dept                            0
department_title                0
char_                           0
character_title                 0
sub_obj                         0
sub_obj_title                   0
vendor_name                     0
doc_ref_no_prefix               0
doc_ref_no_prefix_definition    0
contract_number                 0
contract_description            0
transaction_amount              0
dtype: int64
Updated dataset saved to: C:\Users\Nutzer\Desktop\BAExperiment\filled_data.csv
